name: grey_eco_server

services:
  steamcmd:
    image: grey_eco_server
    domainname: eco_server
    container_name: eco_server
    platform: linux/amd64
    build:
      context: ./
    volumes:
      - steamcmd_login_volume:/home/steam/Steam
      - steamcmd_volume:/home/steam/steamcmd
      - eco_server_logs:/home/steam/eco_server/Logs
      - eco_server_storage:/home/steam/eco_server/Storage
      - ./Configs:/home/steam/eco_server/Configs
    command:
      /home/steam/eco_server/EcoServer -userToken=${ECO_TOKEN}
    ports:
      - "3000:3000/udp"
  nginx:
    image: "nginx:1.27.5-alpine-slim"
    container_name: nginx
    environment:
      NGINX_ENTRYPOINT_LOCAL_RESOLVERS: yes
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl/certificates:/etc/letsencrypt
      - ./nginx/ssl/challenge:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"


volumes:
  steamcmd_volume:
    driver: local
    name: eco_server_steamcmd
  steamcmd_login_volume:
    driver: local
    name: eco_server_steamlogin
  eco_server_logs:
    driver: local
    name: eco_server_logs
  eco_server_storage:
    driver: local
    name: eco_server_storage
